trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/'
    backendType: 'selfConfigured'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/'
    environmentServiceName: 'Pay-As-You-Go(1a1111b1-6644-4109-9949-2dec5f9e7c09)'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/'
    environmentServiceName: 'Pay-As-You-Go(1a1111b1-6644-4109-9949-2dec5f9e7c09)'
    allowTelemetryCollection: true
